### ISSUE TITLE
Wiki description is unclear

### ISSUE THREAD

**Issue by janisz** [dhruvvyas90/qemu-rpi-kernel#1]
Hi

Thanks for posting rPI kernel for quemu. I have problem runing it. I cloned this repo, and ran:

    qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -hda kernel-qemu

 Qemu is launching and I see some logs, but after a while it goes down. When I remove `-no-reboot` option it gets into rebooting loop.

Can you help me
Thanks

**Comment by SaeidYazdani** [comment]
I think you did something wrong... -hda switch should point to the raspberry pi image.... but you have pointed it to the kernel again. You need something like this:

qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -hda name-of-your-rasp-image.img

**Comment by dhruvvyas90** [comment]
Like SaeidYazdani suggested, .img file of your rootfs should be passed as -hda parameter.

**Comment by janisz** [comment]
@SaeidYazdani @dhruvvyas90 Thanks, I downloaded small image and it's working.
