### ISSUE TITLE
Outdated for 4.1.18

### ISSUE THREAD

**Issue by robajz** [dhruvvyas90/qemu-rpi-kernel#10]
Hello, thanks for the great archeology work! :o)

I've followed the build script for current Linux 4.1.18 version and apparently, the script and patch are outdated:

```
git checkout 77798915750db46f10bb449e1625d6368ea42e25
fatal: reference is not a tree: 77798915750db46f10bb449e1625d6368ea42e25
```

The patch did not apply fully and [some other tweak is needed for the MMC BCM2835 driver](https://askubuntu.com/a/628266/44807).

See https://github.com/robajz/qemu-rpi-kernel for changes that got me through it.

Kind regards, Rob

**Comment by eddywebs** [comment]
Hi @robajz and @dhruvvyas90 I am trying to emulate the latest (At the time if writing) 2016-02-26-raspbian-jessie-lite.zip along with kernel-qemu-4.1.13-jessie kernel however the qemu keeps on re-booting up with below messages in terminal. Any idea why ? 
`WARNING: Image format was not specified for '2016-02-26-raspbian-jessie-lite.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
Uncompressing Linux... done, booting the kernel.`

**Comment by dhruvvyas90** [comment]
@eddywebs : Did you perform changes in .img as mentioned over [ here ](https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.1.x-kernel)?

**Comment by dhruvvyas90** [comment]
@robajz : Feel free to submit a PR with necessary changes.
