### ISSUE TITLE
How to emulate Raspberry Pi 3 or higher version?

### ISSUE THREAD

**Issue by zanazakaryaie** [dhruvvyas90/qemu-rpi-kernel#103]
Hello

The tutorials mention to use `-cpu arm1176 -m 256`. I think these are even slower than raspberry pi zero. How can I config it for raspberry 3 or higher version?

**Comment by zwhitchcox** [comment]
I'm working on rpi4 ..will this work with this, I would also like to know? Would be good to include this in readme probably

**Comment by homdx** [comment]
Console version:
https://github.com/wimvanderbauwhede/limited-systems/wiki/Debian-%22buster%22-for-Raspberry-Pi-3-on-QEMU

**Comment by dhruvvyas90** [comment]
@zanazakaryaie : Try instructions under `native-emulation` subfolder. Qemu now supports raspi2/3 machine that can be used to emulate rpi directly without having to use modified kernels.
