### ISSUE TITLE
how do i emulate kano os  using qemu and this kernel

### ISSUE THREAD

**Issue by bukyapavankumar** [dhruvvyas90/qemu-rpi-kernel#108]
i want to emulate kano os which is based on raspbian .
https://kano.me/row/downloadable

you can find kano os images above for pi1,pi2,pi3.

however i couldnt able to boot kano os suceesfully .anyhelp is appreciated.

**Comment by dhruvvyas90** [comment]
@bukyapavankumar : Please consider following instructions under `native-emulation` folder on how to emulate img file using raspi2/3 machine on qemu.

**Comment by bukyapavankumar** [comment]
WL try it thanks.is this newly added?

**Comment by dhruvvyas90** [comment]
Yes.

**Comment by bukyapavankumar** [comment]
> Yes.

qemu-system-aarch64: -device usb-mouse: No 'usb-bus' bus found for device 'usb-mouse'
.
how do i fix this .and also keyboard not working.

**Comment by bukyapavankumar** [comment]
@dhruvvyas90  i can only get this far
![Screenshot from 2020-10-14 22-25-27](https://user-images.githubusercontent.com/25202276/96026421-18342d80-0e74-11eb-9726-6532036c7ba6.png)
