### ISSUE TITLE
Should USB work with any of the kernels?

### ISSUE THREAD

**Issue by dims12** [dhruvvyas90/qemu-rpi-kernel#110]
I tried varios combinations of kernels and dtbs but always have

```
# lsusb
unable to initialize libusb: -99
```

and unable to access USB devices. Is it possible to configure them?

**Comment by dhruvvyas90** [comment]
@dims12 : You have specify in qemu argument which usb devices you would want to use with emulation. Here's some resources on how to do so. (https://qemu.readthedocs.io/en/latest/system/usb.html)
