### ISSUE TITLE
How to use more memory in emulated system

### ISSUE THREAD

**Issue by cmonty14** [dhruvvyas90/qemu-rpi-kernel#112]
Hi,

_-M versatilepb_ restrict the memory configuration to be no more than 256MB.

In order to increase available memory my idea is now to add a file located in host's temporary filesystem and configure this as clients swap.

In Arch Linux, I created this file with
`qemu-create -f raw /tmp/qemutmp/swap.img 256M
`

Now the question is how to add this raw file to QEMU when starting the emulated system?

Adding this option to _qemu-system-arm_
`-drive "file=/tmp/qemutmp/swap.img,if=none,index=1,media=disk,format=raw,id=disk1"`
is not working, means there's no additional drive after starting the system.

Can you please advise how to get this additional drive working?

THX

**Comment by dhruvvyas90** [comment]
Qemu now support raspi2/3 machine emulation natively. Please check native-emulation folder on the repo.
