### ISSUE TITLE
Native Emulation Usb Error

### ISSUE THREAD

**Issue by Cyril-Nachbaur** [dhruvvyas90/qemu-rpi-kernel#114]
Hello,

Thanks a lot for this work !

I used the native emulation folder to emulate a RaspberryPi3+ as your exemple.
But when I run it, I have the error "No 'usb-bus' bus found for device 'usb-mouse'.
I tried to find a solution but nothing works for me.
When I remove the lines "-usb -device usb-mouse -device usb-kbd", the emulation works perfectly (but I can't use mouse of course).

Do you have a solution please ?

Thanks a lot.

**Comment by dhruvvyas90** [comment]
@Cyril-Nachbaur : You will need Qemu version 5.1+ to make usb devices work.

**Comment by bukyapavankumar** [comment]
> @Cyril-Nachbaur : You will need Qemu version 5.1+ to make usb devices work.

how to check qemu version
qemu -v ,qemu --version ?

**Comment by Cyril-Nachbaur** [comment]
I have updated Qemu to version 5.1+.
I have no more errors now, but my mouse doesn't work anyway

**Comment by bukyapavankumar** [comment]
> I have updated Qemu to version 5.1+.
> I have no more errors now, but my mouse doesn't work anyway

i have mouse issues too on qemu 5.1.0.

**Comment by Cyril-Nachbaur** [comment]
@dhruvvyas90 
Do you have any idea please ?
No errors with QEMU 5.1+, but it doesn't work anyway.
I tried a lot of different commands, a mouse is displayed but it doesn't move.
I really can't get this mouse working in the Raspbian Desktop.

**Comment by bukyapavankumar** [comment]
@Cyril-Nachbaur  mouse is working fine on raspberry os. i have problem only in kano os.

**Comment by Cyril-Nachbaur** [comment]
@bukyapavankumar 
Did you use the same command as in the Repo to make the mouse work with raspberry OS ?

**Comment by bukyapavankumar** [comment]
@Cyril-Nachbaur Yes same command  . It worked fine on raspberry os latest.

**Comment by Cyril-Nachbaur** [comment]
I solved my problem, the image used needs to be recent ( at least the 2020-05-27 version of Raspi OS)
