### ISSUE TITLE
Kernel panic on poweroff

### ISSUE THREAD

**Issue by dilyanpalauzov** [dhruvvyas90/qemu-rpi-kernel#122]
With Qemu 5.2 I start

qemu-system-arm -dtb ./versatile-pb-buster.dtb -kernel ./kernel-qemu-4.19.50-buster -cpu arm1176 -m 256 -M versatilepb -append "root=/dev/sda2 rootfstype=ext4 rw" -drive driver=raw,file=./2021-01-11-raspios-buster-armhf.img,index=0,media=disk -serial stdio

then I log in and type “sudo poweroff”.  The system prints:

[  OK  ] Stopped Create System Users.
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
[  OK  ] Started Power-Off.
[  OK  ] Reached target Power-Off.
reboot: System halted
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000

CPU: 0 PID: 1 Comm: systemd-shutdow Not tainted 4.19.50+ #1
Hardware name: ARM-Versatile (Device Tree Support)
[<c001d230>] (unwind_backtrace) from [<c00190ac>] (show_stack+0x10/0x14)
[<c00190ac>] (show_stack) from [<c0025f14>] (panic+0xc8/0x240)
[<c0025f14>] (panic) from [<c0028444>] (do_exit+0x950/0x9fc)
[<c0028444>] (do_exit) from [<c0042440>] (sys_reboot+0x1a0/0x1f0)
[<c0042440>] (sys_reboot) from [<c0009000>] (ret_fast_syscall+0x0/0x54)
Exception stack(0xcf823fa8 to 0xcf823ff0)
3fa0:                   00000000 00000000 fee1dead 28121969 4321fedc f07d4700
3fc0: 00000000 00000000 00000000 00000058 00000fff bebc7c08 00000000 004f4b80
3fe0: 00506e3c bebc7b88 004f14a8 b6ecca38
---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
 ]---

Can you provide hints how to achive clean termination, rather than kernel panic?

**Comment by ptrsr** [comment]
https://gitlab.com/qemu-project/qemu/-/issues/64

**Comment by ptrsr** [comment]
This has been fixed in QEMU [v6.1.0-rc0](https://gitlab.com/qemu-project/qemu/-/tags/v6.1.0-rc0).

**Comment by dhruvvyas90** [comment]
Patched in Qemu 6.1
