### ISSUE TITLE
Native emulation issue with latest QEMU

### ISSUE THREAD

**Issue by RaviBeagle** [dhruvvyas90/qemu-rpi-kernel#123]
Hi Dhruv,

I have a jetson nano (arm64 SBC) and I want to check the native emulation performance.
I have Ubunut 20.04 with KVM enabled kernel running

However QEMU crashes with "Illegal Instruction" during kernel boot. I have a built latest QEMU from sources:

./qemu-system-aarch64 --version
QEMU emulator version 5.2.50 (v5.2.0-1731-g5b19cb63d9)

When I run as follows:

../build/qemu-system-aarch64 -M raspi3 \
-append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1" \
-dtb ./bcm2710-rpi-3-b-plus.dtb \
-sd /media/96747D21747D0571/JetsonNano/2020-08-20-raspios-buster-armhf-full.img \
-kernel ./kernel8.img \
-m 1G -smp 4 -serial stdio -usb -device usb-mouse -device usb-kbd

I get :
[   74.994834] systemd[1]: Condition check resulted in FUSE Control File System being skipped.
[   76.281274] systemd[1]: Starting Apply Kernel Variables...
         Starting Apply Kernel Variables...
Illegal instruction (core dumped)

When I use GDB I see this:

Thread 8 "qemu-system-aar" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fad7f9ba0 (LWP 28037)]
0x0000007f888ac690 in code_gen_buffer ()
(gdb) bt
#0  0x0000007f888ac690 in code_gen_buffer ()
#1  0x0000005555d7c038 in cpu_tb_exec (tb_exit=<synthetic pointer>, itb=<optimized out>, cpu=0x7fb4502c40)
    at ../accel/tcg/cpu-exec.c:191
#2  cpu_loop_exec_tb (tb_exit=<synthetic pointer>, last_tb=<synthetic pointer>, tb=<optimized out>, cpu=0x7fb4502c40)
    at ../accel/tcg/cpu-exec.c:708
#3  cpu_exec (cpu=cpu@entry=0x7fb4502c40) at ../accel/tcg/cpu-exec.c:819
..

I have just two questions:

1) Is this a problem with QEMU or is there anything specific build or options I need to use. Any specific version of QEMU you suggest.

2) Why is TCG used as the accelerator when KVM is present. Is it possible and how to use KVM ?

Thanks a lot in advance..

**Comment by RaviBeagle** [comment]
This seems a QEMU issue on ARM64. Can be closed.

**Comment by RaviBeagle** [comment]
Some additional notes:

1) There is a bug in QEMU causing the crash. Raised the bug and it should be fixed soon
2) We cannot use KVM for the native emulation as KVM does not support multiple address spaces that Raspi3 requires.

**Comment by pciavald** [comment]
@RaviBeagle can you link said bug report? I'm hitting the same issue, trying to run raspbian on pine64's rockpro64:
```sh
sudo qemu-system-aarch64 \
  -M raspi3 \
  -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1" \
  -dtb extract/bcm2710-rpi-3-b-plus.dtb \
  -kernel extract/kernel8.img \
  -sd 2021-10-30-raspios-bullseye-armhf.img \
  -m 1G \
  -smp 4 \
  -serial stdio \
  -usb \
  -device usb-mouse \
  -device usb-kbd
```
![image](https://user-images.githubusercontent.com/3384097/151070986-1ff8bdb4-a18b-4cbb-86e0-74cfe42d5f5b.png)

**Comment by RaviBeagle** [comment]
I think this bug should be fixed in latest QEMU release. Nevertheless I don't think QEMU can support native emulation of Raspberry devices..
