### ISSUE TITLE
VM won't boot up because of usb bus not being there.

### ISSUE THREAD

**Issue by FreddyFeuerstein** [dhruvvyas90/qemu-rpi-kernel#124]
When i try to run the final command to start the raspberry pi 3 vm, it gives me the following error:
No 'usb-bus' bus found for device 'usb-mouse'
My version of raspbian is buster and my version of qemu-system-aarch64 is 4.2.1.

**Comment by dhruvvyas90** [comment]
Try using qemu version 5.2+.

**Comment by FreddyFeuerstein** [comment]
I compiled the newer qemu version and it worked like it should. Thank you.

**Comment by dhruvvyas90** [comment]
Glad to hear that it works with newer qemu.
