### ISSUE TITLE
Boot silently fails

### ISSUE THREAD

**Issue by chrisspen** [dhruvvyas90/qemu-rpi-kernel#13]
Using an [Ubuntu ARM](https://wiki.ubuntu.com/ARM/RaspberryPi), step 1 from the wiki doesn't seem to do anything. I'm running:

    qemu-system-arm -kernel kernel-qemu-4.1.13-jessie \
                -cpu arm1176 \
                -m 256 \
                -M versatilepb \
                -no-reboot \
                -serial stdio \
                -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" \
                -hda 2015-04-06-ubuntu-trusty.img

A window pops up showing the Linux boot screen, and my localhost terminal shows:

    pulseaudio: set_sink_input_volume() failed
    pulseaudio: Reason: Invalid argument
    pulseaudio: set_sink_input_mute() failed
    pulseaudio: Reason: Invalid argument
    Uncompressing Linux... done, booting the kernel.

but then the popup window closes and qemu seems to exit without any further errors. Is this correct?

**Comment by dhruvvyas90** [comment]
Did you modify `fstab` entries as per this post : https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.1.x-kernel before using it ? I've never tried emulating ubuntu, but it should just work.

**Comment by chrisspen** [comment]
I missed that link. That was it. Thanks.
