### ISSUE TITLE
Kernel image and dtb files for raspi3 emulation

### ISSUE THREAD

**Issue by manas-modi100** [dhruvvyas90/qemu-rpi-kernel#133]
Required kernel images and dtb files for raspi3 emulation are provided in native-emulation folder. Then, why is the step of extracting kernel images and dtb files from img file required?

**Comment by ptrsr** [comment]
It is not required, you will be able to start up a distro image using the provided kernel and dtb files. However, it is preferred to use the kernel and dtb files from the image itself to prevent a kernel module version mismatch (in which case, a lot of functionalities might not work, such as ethernet). One problem may be that the kernel version of the image might not be supported by QEMU. I'd suggest to use the 5.4.x kernel for now.
