### ISSUE TITLE
Bullseye download

### ISSUE THREAD

**Issue by OrangeDog** [dhruvvyas90/qemu-rpi-kernel#138]
Pi images for Bullseye are now available, it would be good to have a matching kernel (5.10.63) here.
https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/

**Comment by dhruvvyas90** [comment]
Agreed.

**Comment by wooter6928196219911** [comment]
Use the native emulation guide for now.

**Comment by OrangeDog** [comment]
Oh, I didn't see #136 because it was closed.
I just need to build with that config and then make a PR with the result then?

**Comment by dhruvvyas90** [comment]
Thanks for the PR.
