### ISSUE TITLE
Overwriting .config

### ISSUE THREAD

**Issue by chrisspen** [dhruvvyas90/qemu-rpi-kernel#14]
Is the sequence in build-kernel-qemu correct?

You append some custom parameters to `.config` but then you run:

    make -j 4 -k ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- menuconfig

which overwrites this file and removes most of those values. Should that order be reversed? Why are you appending those parameters if they're just being removed?

Also, I see you're using the `arm-linux-gnueabihf` toolchain, but the archived "compiling-a-kernel" article uses `arm-linux-gnueabihf-` making explicit note to "not forget the '-' at the end of this string". Does this matter?

Also, when I run:

    make -j 4 -k ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- bzImage

it prompts me a thousand times for N/m/y/? for various options. How do I disable this?

**Comment by dhruvvyas90** [comment]
@chrisspen: I think it's correct. It works fine for me on my linux box.

**Comment by chrisspen** [comment]
It doesn't prompt you? I followed your instructions exactly, so either it doesn't work at all on Ubuntu, or there's something missing from your instructions.

**Comment by dhruvvyas90** [comment]
Hi, @chrisspen: It doesn't prompt. Not sure, what's at play in your particular case. Are you still facing the same problem ?

**Comment by tomerb** [comment]
You can do make olddefconfig, to not be prompted (default settings will be automatically applied).

**Comment by dhruvvyas90** [comment]
@chrisspen: Can you try "make olddefconfig" as per tomerb's comment above ?

**Comment by chrisspen** [comment]
Sorry, this process became too burdensome and time-consuming, so I've abandoned my attempt to virtualize an RPi. Thanks for your help though.
