### ISSUE TITLE
None of these kernels work with the raspian_latest

### ISSUE THREAD

**Issue by johnjelinek** [dhruvvyas90/qemu-rpi-kernel#15]
![qemu](https://cloud.githubusercontent.com/assets/873610/15546721/9883f6a4-2266-11e6-99ac-cb8ce64b382e.png)
This is what I see, with all the jessie kernels in this repo. The website says latest kernel is `4.4`. Should I build my own?

**Comment by applyhhj** [comment]
You can follow this https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.1.x-kernel to solve the problem.

Best regards!


2016-05-26 







发件人：John Jelinek IV <notifications@github.com>
发送时间：2016-05-26 00:01
主题：[dhruvvyas90/qemu-rpi-kernel] None of these kernels work with the raspian_latest (#15)
收件人："dhruvvyas90/qemu-rpi-kernel"<qemu-rpi-kernel@noreply.github.com>
抄送：


This is what I see, with all the jessie kernels in this repo. The website says latest kernel is 4.4. Should I build my own?

**Comment by dhruvvyas90** [comment]
@johnjelinek: Were you able to run repo kernels with the latest images after following wiki ?

**Comment by johnjelinek** [comment]
I haven't tried it yet with the instructions from the wiki

**Comment by chiwanpark** [comment]
I have a same problem and instruction in wiki doesn't work for me.

**Comment by dhruvvyas90** [comment]
@chiwanpark: Can you tell me which Raspbian image is failing to boot ? It's important to note that offset number mentioned in step #1 differs for each image.

**Comment by chiwanpark** [comment]
I used Raspbian Jessie Lite image from https://www.raspberrypi.org/downloads/raspbian/ here. I downloaded it yesterday. It seems that I need to re-compile 4.4 kernel.

**Comment by chiwanpark** [comment]
Here is partition table information:

```
Disk: 2016-05-27-raspbian-jessie-lite.img	geometry: 672/64/63 [2709504 sectors]
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
 1: 0C    0 130   3 -    8 138   2 [      8192 -     129024] Win95 FAT32L
 2: 83    8 138   3 -  168 167  63 [    137216 -    2572288] Linux files*
 3: 00    0   0   0 -    0   0   0 [         0 -          0] unused      
 4: 00    0   0   0 -    0   0   0 [         0 -          0] unused      
```

**Comment by chiwanpark** [comment]
I succeeded booting with re-compiled kernel based on `rpi-4.4.y` branch.

**Comment by dhruvvyas90** [comment]
@chiwanpark: That's great news. Can you fork this repo, add compiled kernel from 4.4.y branch and create a pull request ? I didn't have a chance to test this issue since I currently don't have any linux box with me. Will give it a shot next week. Thanks.

**Comment by chiwanpark** [comment]
Okay, I'll send a PR in tomorrow. :-)

**Comment by dhruvvyas90** [comment]
@chiwanpark: Thanks a lot. Appreciate your efforts. :)

**Comment by dhruvvyas90** [comment]
@johnjelinek: You should be able to emulate the latest image with 4.4.11 kernel.

**Comment by jeffforbes** [comment]
I am unable to get the latest (2016-05-27) regular jessie or lite jessie images to boot with the 4.4.11-jessie kernel. The screen output is like the first comment, except for the lin:
CPU: 0 PID: 1 Comm: bash Not tainted  4.4.12+ #3
I am using qemu-system-arm under Fedora 23, if that makes a difference.
Any suggestions as to what may be the problem?

**Comment by chiwanpark** [comment]
@jeffforbes Did you modify your jessie (or jessie lite) images with instructions in [wiki](https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.x.xx-kernel)?

**Comment by jeffforbes** [comment]
No I did not, since I am unable to reach that page from the root of the wiki.
The information in your link above did allow the image to boot. 
Thank you.

**Comment by dhruvvyas90** [comment]
@chiwanpark: Thank you for your support. :) @jeffforbes: I'm glad that it's working now.
Closing this issue since it's been fixed with the latest commit by @chiwanpark.

**Comment by dhruvvyas90** [comment]
@chiwanpark: Can you post your config file which you used to compile the kernel if you have it handy ? Thanks.

**Comment by chiwanpark** [comment]
Unfotunately, I removed the virtual machines to be used to create the kernel image. Sorry.
