### ISSUE TITLE
How to properly use physical microSD instead of an image?

### ISSUE THREAD

**Issue by mrdc** [dhruvvyas90/qemu-rpi-kernel#157]
Hello,

I'm trying to use physical microSD from my RPi for debugging. At the moment I have an issue passing physical microSD to qemu using these additional arguments`-drive file=/dev/disk13,if=none,format=raw` and ` -append "root=/dev/mmcblk0p7 rootfstype=ext4"`
disk13 is the physical microSD, /dev/mmcblk0p7 is root partition for RaspberryOS, qemu boots the kernel, but then I receive Kernel Panic, because it can't find root partition:
```
[    2.715128] VFS: Cannot open root device "mmcblk0p7" or unknown-block(0,0): error -6
[    2.715856] Please append a correct "root=" boot option; here are the available partitions:
[    2.716698] 0100            4096 ram0 
[    2.716746]  (driver?)
[    2.716996] 0101            4096 ram1 
[    2.717016]  (driver?)
[    2.718510] 0102            4096 ram2 
[    2.718532]  (driver?)
[    2.718744] 0103            4096 ram3 
[    2.718762]  (driver?)
[    2.719030] 0104            4096 ram4 
[    2.719048]  (driver?)
[    2.719880] 0105            4096 ram5 
[    2.719918]  (driver?)
[    2.720546] 0106            4096 ram6 
[    2.720562]  (driver?)
[    2.720752] 0107            4096 ram7 
[    2.720768]  (driver?)
[    2.720956] 0108            4096 ram8 
[    2.720972]  (driver?)
[    2.722830] 0109            4096 ram9 
[    2.722852]  (driver?)
[    2.723214] 010a            4096 ram10 
[    2.723294]  (driver?)
[    2.724030] 010b            4096 ram11 
[    2.724056]  (driver?)
[    2.724530] 010c            4096 ram12 
[    2.724550]  (driver?)
[    2.724744] 010d            4096 ram13 
[    2.724762]  (driver?)
[    2.724968] 010e            4096 ram14 
[    2.725448]  (driver?)
[    2.725838] 010f            4096 ram15 
[    2.725856]  (driver?)
[    2.726386] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

```
I've tried -hda for qemu, different variants in -append "root=/dev/sda2" etc. Out of ideas what can be wrong - not a frequent qemu user for such scenarios. Qemu docs haven't helped, also for googling - everybody uses images, but not physical microSD.

**Comment by dhruvvyas90** [comment]
Hi, I don't have first-hand experience but maybe give this (https://forums.raspberrypi.com/viewtopic.php?t=45118 ) a read and see if it works.

**Comment by mrdc** [comment]
> Hi, I don't have first-hand experience but maybe give this (https://forums.raspberrypi.com/viewtopic.php?t=45118 ) a read and see if it works.

Hi, thanks! I’ve searched everywhere - including the link you’ve shared. For me it fails, because the size of a microSD is not multiple 2. So, in this case a special syntax for arguments is required, which I can’t find for physical devices (including QEMU documentation - which is strange, but they don’t provide enough examples).
The other option is to patch QEMU sources and build the custom version.
I’ve choose the third option - made an image of my microSD :D
