### ISSUE TITLE
Version labeled as 4.4.11 appears to be 4.4.12.

### ISSUE THREAD

**Issue by glama** [dhruvvyas90/qemu-rpi-kernel#17]
Message 
COmm: swapper Not tainted 4.4.12+

**Comment by WuTianming** [comment]
Kernel panic: Comm: bash Not tainted 4.4.12+

**Comment by dhruvvyas90** [comment]
I confirm this issue and fixed it by the latest commit.

**Comment by punkpeye** [comment]
@glama Off chance that you see this message, could you email me at frank@glama.ai ?
