### ISSUE TITLE
CONFIG_FHANDLE=y missing

### ISSUE THREAD

**Issue by bablokb** [dhruvvyas90/qemu-rpi-kernel#18]
With jessie, boot fails if you have additional mountpoints in /etc/fstab. This seems to be related to a number of kernel-config parameters which systemd needs but your kernel does not provide, especially CONFIG_FHANDLE. 

Note this is not a qemu/raspbian specific issue, see  [http://forums.debian.net/viewtopic.php?f=10&t=118828](url) for a discussion and additional links (at the bottom of the page).

I'm happy to test a new kernel with (at least) CONFIG_FHANDLE=y, but I currently don't have the time to setup a cross-compile environment for my own kernel.

Bernhard

**Comment by cbirchinger** [comment]
The CONFIG_FHANDLE parameter is also required for systemd to start serial gettys. Without the option it'll timeout the service on boot.

The option would really help to start without graphics ("-nographic") and "console=ttyAMA0" which gives
you a getty on the current terminal and doesn't need any graphical window.

I'm not fully sure, but i think CONFIG_FHANDLE is listed as requirement for systemd based systems anyway.

**Comment by ferbar** [comment]
included in #25

**Comment by dhruvvyas90** [comment]
Solved by PR #25
