### ISSUE TITLE
Typo in wiki link to emulating Jessie

### ISSUE THREAD

**Issue by taufiqkh** [dhruvvyas90/qemu-rpi-kernel#19]
The [home](https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki) wiki page link to `Emulating-Jessie-image-with-4.1.x-kernel` is broken, link should be to `Emulating-Jessie-image-with-4.x.xx-kernel`.

**Comment by dhruvvyas90** [comment]
Fixed wiki.
