### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by SaeidYazdani** [dhruvvyas90/qemu-rpi-kernel#2]
Thanks a lot for your efforts. I have now a fully working raspberry pi emulated in my Ubuntu using the kernel you provided.

I have some questions:
What is the version of kernel you have compiled?
If we want to do this ourselves, what are the steps? Can you please provide a guide or something?

Thanks again and keep it up!

**Comment by dhruvvyas90** [comment]
If I remember clearly, it was 3.10.something kernel. You can always check which version of kernel you're running by `uname -a` command on qemu terminal. It should list out kernel version. 

As far as, compiling guide is concerned, you can follow these guides.

https://web.archive.org/web/20131210001638/http://xecdesign.com/compiling-a-kernel/
https://web.archive.org/web/20131209235952/http://xecdesign.com/compiling-qemu/
https://web.archive.org/web/20131210001407/http://xecdesign.com/working-with-qemu/
https://web.archive.org/web/20131210001526/http://xecdesign.com/qemu-emulating-raspberry-pi-the-easy-way/

You can also try, torlus' qemu which allows you to emulate Rpi kernel without any modification. Link : https://github.com/Torlus/qemu/tree/rpi 

Hope it helps.
