### ISSUE TITLE
build-kernel-qemu fails to build a running 4.4.11 kernel

### ISSUE THREAD

**Issue by ferbar** [dhruvvyas90/qemu-rpi-kernel#21]
Hi,

when I try to build a kernel for raspberrypi-kernel-20160620 qemu refuses to start the kernel with:

> Error: unrecognized/unsupported processor variant (0x410fb767).

I think there are config options missing in the build script. Do you have the kernel config for the 4.4.12 kernel? thx!

**Comment by ferbar** [comment]
this kernel config works:
https://github.com/rimmington/qemu-rpi-kernel/blob/docker/tools/build-kernel-qemu

Iask you to enable /proc/config.gz:

CONFIG_IKCONFIG=y
CONFIG_IKCONFIG_PROC=y

**Comment by dhruvvyas90** [comment]
@ferbar: Can you create a pull request to add this new config file under tools section ? Appreciate it.

**Comment by ferbar** [comment]
see #25 
thx!

**Comment by dhruvvyas90** [comment]
Merged.
