### ISSUE TITLE
Script to run img with qemu

### ISSUE THREAD

**Issue by EdgarOliveira** [dhruvvyas90/qemu-rpi-kernel#22]
Hello,

Share with us this script, I relied in this article (http://dhruvvyas.com/blog/?p=49) to built this: https://github.com/EdgarOliveira/scriptlinux/blob/master/qemu_choose_vm.sh

I hope it is advantageous for you
ENO

**Comment by dhruvvyas90** [comment]
@EdgarOliveira: You can add that script to the tools folder and send me a pull request.

**Comment by EdgarOliveira** [comment]
@dhruvvyas90 Hello, thank you for you interest. I think did a pull request, please confirm me, because I am a newbie in github and some tools I don't know!

**Comment by dhruvvyas90** [comment]
Merged. :) You can probably make necessary changes in wiki as well, that utilises your script well. Once you are done, lemme know. I will have a look at good. Good work. :)
