### ISSUE TITLE
How can I use -M raspi2 with this kernel?

### ISSUE THREAD

**Issue by ICHx** [dhruvvyas90/qemu-rpi-kernel#28]
I do not know if I should use the kernel7.img or the kernel image from this repo, but I tried many times with no success

.\bin\qemu-system-armw -M raspi2 -kernel kernel-qemu-4.4.34-jessie -hda rasp.qcow -append "rw earlyprintk  dwc_otg.lpm_enable=0 root=/dev/sda2 init=/bin/sh" -dtb bcm2709-rpi-2-b.dtb -usbdevice mouse -usbdevice keyboard -serial stdio
.\bin\qemu-system-armw -M raspi2 -kernel kernel7.img -sd rasp.qcow -append "rw earlyprintk console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 nomodeset  init=/bin/sh" -dtb bcm2709-rpi-2-b.dtb -usbdevice mouse -usbdevice keyboard -serial stdio

**Comment by dhruvvyas90** [comment]
@ICHx: Kernels on these repo only work with qemu machine versatilepb (-M versatilepb), since qemu didn't have Rpi machine support initially. As far as second, command goes, try removing init=/bin/sh and see if it works. With -M raspi2 kernel7.img should work out of the box. Hope it helps.

**Comment by alexander-behring** [comment]
@ICHx: You might try to start out from my command line:
qemu-system-arm -kernel kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -machine versatilepb -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw vga=normal console=ttyAMA0" -drive "file=/data/raspbian-jessie-lite.img,index=0,media=disk,format=raw" -no-reboot -serial stdio -curses
Funny thing - MSDN has a quite good tutorial on this [LINK](https://blogs.msdn.microsoft.com/iliast/2016/11/10/how-to-emulate-raspberry-pi/).

**Comment by dhruvvyas90** [comment]
@ICHx: Do the recent comments solve your problem ? Like I said, if qemu added machine support for Raspberry pi 2, it should work out of the box with kernel7.img fetched from raspberry pi without needing any modifications in kernel. I couldn't find any documentation on machine support by qemu on raspberry pi. May be you're trying out the famous torlus qemu fork. If it is the first case, do let me know by commenting proper link. It would be interesting to follow that thread. - Dhruv.

**Comment by ajgriesemer** [comment]
@ICHx might be referring to the raspi2 machine that was added in version 2.6. Unfortunately, according to the changelogs it doesn't like like you should expect much from it.

[From Change Log 2.6 ](http://wiki.qemu-project.org/ChangeLog/2.6)
> New partial Raspberry Pi 2 emulation with "raspi2" machine type. For now, it can boot older releases of Windows and Raspbian, but lacks a number of devices including USB.

[From Known Issues section of Change Log 2.7 ](http://wiki.qemu-project.org/ChangeLog/2.7)

> Missing device emulations for Raspberry Pi: GPIO, MMCI0, RNG (maybe more). Therefore current Raspbian kernels won't boot.

**Comment by dhruvvyas90** [comment]
@ICHx : I'm closing this issue since it doesn't versatilepb machine as we use in here.

**Comment by aatishnn** [comment]
@ICHx were you able to use the raspi2 machine type?

**Comment by ICHx** [comment]
Nope, and have not tried recently

**Comment by ve2tmq** [comment]
Hi folks, I try to build kernel as versatilepb or user kernel.img directly from image (with -M raspi2) both give a black screen.  With kernel-qemu-4.4.34 it's works good.  I need new kernel to fit with modules on image.  I don't know what's wrong.  Do you see same issue on your test?

**Comment by asgmeonerandom** [comment]
> Hi folks, I try to build kernel as versatilepb or user kernel.img directly from image (with -M raspi2) both give a black screen. With kernel-qemu-4.4.34 it's works good. I need new kernel to fit with modules on image. I don't know what's wrong. Do you see same issue on your test?

I got black screen too! REVIVE THIS THREAD

**Comment by eirikb** [comment]
@asgmeonerandom 
Not sure if this is the correct place to post this, but this works for me running arch linux:
```bash
qemu-system-arm \
    -M raspi2 \
    -kernel b/kernel7.img \
    -drive "format=raw,file=arch.img" \
    -append "console=ttyAMA0 root=/dev/mmcblk0p2 rw rootwait" \
    -dtb b/bcm2709-rpi-2-b.dtb
```

Full demo (including creating image, where the kernel comes from etc.): https://gist.github.com/eirikb/5bbf85d935c512827f859b614799de94
