### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Seraphime** [dhruvvyas90/qemu-rpi-kernel#29]
Hi, I wanted to thank you for those kernels. We end up using them quite a lot.

Do you think it would be possible to do a release of the latest kernel hosted here, so there may be an easy and uniform way to fetch it ?

Thanks

**Comment by dhruvvyas90** [comment]
@Seraphime: Hello, I appreciate that kernels on this repo help you a lot, but I didn't quite understand the later part of your comment. Do you want to contribute new kernels to this repository ? If that's what you mean, you're most welcome.

**Comment by dhruvvyas90** [comment]
@Seraphime: Since there is no reply from op on this issue, I'm closing this issue.
