### ISSUE TITLE
4.9 Kernel patch

### ISSUE THREAD

**Issue by ajgriesemer** [dhruvvyas90/qemu-rpi-kernel#30]
It looks like Raspbian is getting ready to move to the 4.9 kernel sometime soon 
https://www.raspberrypi.org/forums/viewtopic.php?t=167934

Have you looked into porting these fixes to the 4.9 kernel? I ran a quick test to see if the patch would apply on the current 4.9 Raspberry Pi kernel and it failed.

**Comment by dhruvvyas90** [comment]
@ajgriesemer: Hi, I believe that it would still take some time for 4.9.0 to arrive. Once organization releases it officially, I will try to build the kernel for Qemu.

**Comment by guysoft** [comment]
Hey, The current kernel is 4.9.35, is there a way to build it now?
Can you give me some general instructions how to build it myself?
(Also, should this be reopened?)

**Comment by sej7278** [comment]
i'd be interested in this too, at the moment there's no way to use qemu on a recent raspbian jessie image (other than systemd-nspawn which doesn't even use the rpi kernel).
