### ISSUE TITLE
Unable to Boot R Pi Jessie in QEMU

### ISSUE THREAD

**Issue by drkurrey** [dhruvvyas90/qemu-rpi-kernel#32]
> # I am trying to run Raspbian Jessie in Ubuntu 16.04 using QEMU Emulator.

The Configuration file has the following content.

> #!/bin/bash
#Starts raspberry pi image in configuration mode
qemu-system-arm -kernel ./qemu-rpi-kernel/kernel-qemu-4.4.34-jessie /-cpu arm1176 /m 256 /M versatilepb /no-reboot /serial stdio /append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -hda rpiJessie.img

When the config file is made to run it shows the following

> ![screenshot`from 2017-04-21 16-14-00](https://cloud.githubusercontent.com/assets/27806985/25274472/c94fa4c6-26ad-11e7-8e3e-147c9a316acd.png)

I have done what I could. But, still no solution.

**Comment by drawkula** [comment]
I got curious and just tried it in Debian-8.6 using a freshly homegrown `qemu-v2.9.0`.

Using your script as starting point, I changed all stuff that looked strange to me or/and which Qemu complained about. Ok... and there are still some Qemu warnings, but that can be ironed away later...

With the following starter script I get Raspbian/jessie booted...
```
#!/bin/sh
export LANG=
exec /opt/qemu/latest/bin/qemu-system-arm \
        -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio \
        -kernel kernel-qemu-4.4.34-jessie \
        -append "root=/dev/sda2 panic=1 rootfstype=ext4 ro" \
        -hda sda.img
```
This is not the "configure mode starter" but you'll know what to change... ;-)

Proof:

![20170421-115805-gmt--raspbian-jessie-in-qemu](https://cloud.githubusercontent.com/assets/9768622/25276596/850cf534-268a-11e7-9be9-5eeaac3381c9.png)

**Comment by drkurrey** [comment]
@drawkula, the configuration provided by you is not working in my pc.

**Comment by electronoob** [comment]
using a kernel from this repo along with latest jessie lite image of raspbian, qemu booted into linux fine. (okay, windows as host but im sure that doesnt make any difference here).

![screen shot](https://i.imgur.com/RRvULJQ.png)

    qemu-system-arm.exe -M versatilepb -cpu arm1176 -hda 2017-04-10-raspbian-jessie-lite.img -kernel kernel-qemu-4.4.34-jessie -m 192 -append "root=/dev/sda2"

**Comment by OutsourcedGuru** [comment]
For what it's worth, I'm running on Ubuntu 16.04LTS, attempted to follow the instructions and I appear to be in the same boat.

```
$ qemu-system-arm -kernel kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -M vmpi -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -had raspbian-stretch.img

qemu-system-arm: -had raspbian-stretch.img: unsupported machine type
Use -machine help to list supported machines

$ qemu-system-arm -machine help

```
Supported machines are:
akita                Sharp SL-C1000 (Akita) PDA (PXA270)
borzoi               Sharp SL-C3100 (Borzoi) PDA (PXA270)
canon-a1100          Canon PowerShot A1100 IS
cheetah              Palm Tungsten|E aka. Cheetah PDA (OMAP310)
collie               Sharp SL-5500 (Collie) PDA (SA-1110)
connex               Gumstix Connex (PXA255)
cubieboard           cubietech cubieboard
highbank             Calxeda Highbank (ECX-1000)
imx25-pdk            ARM i.MX25 PDK board (ARM926)
integratorcp         ARM Integrator/CP (ARM926EJ-S)
kzm                  ARM KZM Emulation Baseboard (ARM1136)
lm3s6965evb          Stellaris LM3S6965EVB
lm3s811evb           Stellaris LM3S811EVB
mainstone            Mainstone II (PXA27x)
midway               Calxeda Midway (ECX-2000)
musicpal             Marvell 88w8618 / MusicPal (ARM926EJ-S)
n800                 Nokia N800 tablet aka. RX-34 (OMAP2420)
n810                 Nokia N810 tablet aka. RX-44 (OMAP2420)
netduino2            Netduino 2 Machine
none                 empty machine
nuri                 Samsung NURI board (Exynos4210)
realview-eb          ARM RealView Emulation Baseboard (ARM926EJ-S)
realview-eb-mpcore   ARM RealView Emulation Baseboard (ARM11MPCore)
realview-pb-a8       ARM RealView Platform Baseboard for Cortex-A8
realview-pbx-a9      ARM RealView Platform Baseboard Explore for Cortex-A9
smdkc210             Samsung SMDKC210 board (Exynos4210)
spitz                Sharp SL-C3000 (Spitz) PDA (PXA270)
sx1                  Siemens SX1 (OMAP310) V2
sx1-v1               Siemens SX1 (OMAP310) V1
terrier              Sharp SL-C3200 (Terrier) PDA (PXA270)
tosa                 Sharp SL-6000 (Tosa) PDA (PXA255)
verdex               Gumstix Verdex (PXA270)
versatileab          ARM Versatile/AB (ARM926EJ-S)
versatilepb          ARM Versatile/PB (ARM926EJ-S)
vexpress-a15         ARM Versatile Express for Cortex-A15
vexpress-a9          ARM Versatile Express for Cortex-A9
virt                 ARM Virtual Machine
xilinx-zynq-a9       Xilinx Zynq Platform Baseboard for Cortex-A9
z2                   Zipit Z2 (PXA27x)
```

I tried adding `-machine virt` but that resulted in "...mach-virt: CPU arm1176 not supported".

**Comment by drawkula** [comment]
```
$ qemu-system-arm -kernel kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -M vmpi -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -had raspbian-stretch.img

qemu-system-arm: -had raspbian-stretch.img: unsupported machine type
Use -machine help to list supported machines

```
Maybe you meant `-hda raspbian-stretch.img`?

**Comment by OutsourcedGuru** [comment]
Actually, I typed that correctly in the command line.  I just re-typed it for here.

I'm now walking through the tutorial [here](https://www.raspberrypi.org/forums/viewtopic.php?t=175454) which suggests pre-mounting the image to adjust its `/etc/ld.so.preload` file, commenting out the only line in it.  That one still produced the same error.  I'm now downloading the exact day's version of Jessie that author used (except the Pixel version, presumably, versus his Lite).  Still watching that file download...

**Comment by OutsourcedGuru** [comment]
Unfortunately, downloading and repeating that experiment with the proper version of raspian-jessie.img resulted in the same error as before. I've tried adding "format=raw" to the -append string and also adding "-machine virt" to the very end of the command. Still getting "unsupported machine type", I'm afraid.

It sounds like your Windows-based QEMU install comes with things this doesn't include.  And I've manually done a "sudo apt-get install qemu-system" as well as qemu-kvm, libvirt-bin bridge-utils and virt-manager and qemu (from your tutorial).

**Comment by dhruvvyas90** [comment]
It should work alright given all the instructions on wiki are followed.
