### ISSUE TITLE
qemu locks up

### ISSUE THREAD

**Issue by spike11302000** [dhruvvyas90/qemu-rpi-kernel#34]
qemu seem to lock up mid way thought boot up when trying to boot 2017-04-10-raspbian-jessie

**Comment by joerick** [comment]
What was your QEMU command and what did the logs say before it locked up?

**Comment by nunof** [comment]
I'm not the original reporter but it also happens to me.

Using the following command:
# qemu-system-arm -kernel kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1" -drive file=kernel-qemu-4.4.34-jessie,index=0,media=disk,format=raw -net nic -net tap,ifname=tap0,script=no,downscript=no

See attached.

![rpi-qemu-crash](https://cloud.githubusercontent.com/assets/908443/26574723/513932aa-451a-11e7-8173-319177cb9b7b.png)

**Comment by nunof** [comment]
deleted my previous comment. Sorry for the noise. Instructions in https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.x.xx-kernel work fine for me.

**Comment by dhruvvyas90** [comment]
Sounds good. Closing the issue.
