### ISSUE TITLE
Raspberry Pi Serial Console

### ISSUE THREAD

**Issue by tomkcook** [dhruvvyas90/qemu-rpi-kernel#35]
Is it possible to get the Raspberry Pi serial console redirected to stdio?

I've tried adding `-serial stdio` to the qemu command line and `console=ttyS0` and `console=ttyAMA0` to the kernel command line but with no success - no error message or anything, just no output on stdio.

**Comment by nachoparker** [comment]
you can use `vga=normal console=ttyAMA0`. Look at this code

https://github.com/nachoparker/qemu-raspbian-network/blob/master/qemu-pi.sh#L135

You can just launch the whole thing with this script, with networking and serial console

https://github.com/nachoparker/qemu-raspbian-network

**Comment by dhruvvyas90** [comment]
@tomkcook: This issue should be solved once you add `console=ttyAMA0` in qemu arguments.
