### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by tomkcook** [dhruvvyas90/qemu-rpi-kernel#36]
If I follow this instructions on the wiki, I get working NAT-based networking.

As soon as I try to introduce a bridged network, I can't get anything to work.  I'm adding eg:

```
-netdev tap,helper=/usr/lib/qemu/qemu-bridge-helper,id=hn0 -device e1000,netdev=hn0,id=nic1
```

This boots but there is no network device.  I've tried `virtio-net-pci` with the same result.  `virtio-net-device` and `usb-net` both give error messages about their respective busses not being present.

How can we explicitly configure networking?

**Comment by dhruvvyas90** [comment]
Hi, This seems more like a qemu configuration issue rather than kernel issue. Can you try emulate any other kernel (say ubuntu kernel for x86 ) with ubuntu image and see if you get bridging part working. If yes, that we can dig deeper.

**Comment by tomkcook** [comment]
I've followed this up a bit on the qemu mailing list; the problem seems to be that the kernel has no modules built for it and no suitable drivers built in.  The default network device is a smc91c111 and the kernel has a driver for it, but this can't be added through commandline parameters as it's not a part that can be discovered on a bus.

So, ideally, your `build-kernel-qemu` script would build a decent selection of modules as well as the kernel image (and the selection of webcam modules it can be configured to build at present).  But I've not had time to try to figure out a workable `.config`.

In the long term, it'd be cool to add emulations of the various RPi peripherals to qemu so that eg GPIO and serial lines work, but that's a long way into the future, methinks.

**Comment by nachoparker** [comment]
I provide a script that sets up networking for you. See

https://ownyourbits.com/2017/02/06/raspbian-on-qemu-with-network-access/

**Comment by dhruvvyas90** [comment]
Assuming, the solution provided by @nachoparker  solved your issue.

**Comment by guysoft** [comment]
I can't get @nachoparker 's solution to work. No internet access no matter what I tried so far.

**Comment by nachoparker** [comment]
it works on arch and ubuntu for me

**Comment by tomkcook** [comment]
See attached a .config a Raspberry Pi Linux kernel - this one is for commit 38f2800e6e94019a00a2880bfed8fba37aea2e5d from the RPi Linux git repository.  If you build this & install the modules it creates into your image, then you can add '-net' network interfaces on the commandline and the kernel will load the appropriate driver for them.

Personally, I create a tap interface that I then bridge to my ethernet adapter.  Something like this:

```
$ sudo brctl addbr br0
$ sudo brctl addif br0 eth0
$ sudo ip tuntap add tap0 mode tap user <me>
$ sudo ip link set tap0 up
$ sudo brctl addif br0 tap0
```

then add `-net tap,ifname=tap0` on the qemu command-line.

[config-qemu-rpi.gz](https://github.com/dhruvvyas90/qemu-rpi-kernel/files/1694826/config-qemu-rpi.gz)

**Comment by guysoft** [comment]
@tomkcook But then you are not using the kernel from this repository, am I right?

**Comment by Leadrive** [comment]
ref: https://blog.csdn.net/c80486/article/details/8460755
