### ISSUE TITLE
can I compile a qemu-rpi-kernel for cortex-a7?

### ISSUE THREAD

**Issue by EvaChenn** [dhruvvyas90/qemu-rpi-kernel#39]
Thanks for uploading these qemu-rpi-kernels, I had successfully run a 2017-07-05-raspbian-jessie-lite.img  with kernel-qemu-4.4.34-jessie on versatilepb using qemu-system-arm.

` qemu-system-arm -cpu arm1176 -m 256 -M versatilepb -serial stdio -append "console=ttyAMA0,115200 root=/dev/sda2 panic=1 rootfstype=ext4 rw" -kernel kernel-qemu-4.4.34-jessie -hda 2017-07-05-raspbian-jessie-lite.img`

the above is the command I use

However, I found out that Raspberry Pi 2 use cortex-a7 cpu, not arm1176, the cpu I used in the above command.

Then I changed to use -cpu cortex-a7 but the result is 
`Error: unrecognized/unsupported processor variant (0x410fc075).`

I am wondering if  I have to recompile the kernel for cortex-a7, but I don't have any idea how to do that...
Could you please give me some suggestions? 

Thanks anyway.

**Comment by dhruvvyas90** [comment]
I believe that qemu supports native kernel with Machine flag rpi2. You can try that once.
