### ISSUE TITLE
reboot with Jessie

### ISSUE THREAD

**Issue by rigorm** [dhruvvyas90/qemu-rpi-kernel#4]
Looks like there's a kernel crash with the 2015-09-24 Jessie. the boot sequence reboots.

**Comment by dhruvvyas90** [comment]
@rigorm I believe that this kernel only works with wheezy image. If you find out the solution to make it work with the latest jessie image, feel free to create a PR.

**Comment by dhruvvyas90** [comment]
@rigorm I've compiled and added 4.1.7+ kernel which is compatible with jessie image (ie, it boots fine and all). But there are fewer bugs which are I think image specific and systemd. It sends me to emergency mode upon booting. You can give it a shot.
