### ISSUE TITLE
Newer stable kernel 4.9

### ISSUE THREAD

**Issue by nachoparker** [dhruvvyas90/qemu-rpi-kernel#40]
Hi

Latest Raspbian Stretch came out, featuring kernel 4.9.41

Any plans to share that kernel build? ( I see in #30 that you were waiting for the official Raspbian release )

Many thanks for your work

**Comment by sunqingyao** [comment]
Yeah that would be every helpful! `xecdesign.com` is down and unfortunately not all its pages have been archived, so some required files are missing. (For example, I cannot do `wget http://xecdesign.com/downloads/linux-qemu/linux-arm.patch`)

@dhruvvyas90 , since you have built several kernel images for us, I suppose you have all the required components at hand. It won't be too hard for you to build `kernel-qemu-4.9.41-jessie` for us, right?

**Comment by nachoparker** [comment]
apparently there's a `-M raspi2` option now so you don't need an external kernel. Still haven't tried it though

**Comment by stephanfriedrich** [comment]
## ISSUE 

Hi i got an error on raspberry-pi boot via qemu, something like ```kernel panic - not syncing: vfs: unable to mount root fs...```

my specs are:
- latest raspberrypi image with kernel version 4.9 (2017-09-07-raspbian-stretch-lite.img)
- quemu-rpi-kernel (kernel-qemu-4.4.34-jessie)

my command are:
```
qemu-system-arm -kernel qemu-rpi-kernel/kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -M versatilepb -serial stdio -append "root=/dev/sda2 rootfstype=ext4 rw" -hda 2017-09-07-raspbian-stretch-lite.img 
```

## FIX

**but now it boots raspberian without errors**
to fix the kernel issue, i followed the wiki instructions, especially: **Step 1** (take a loook => https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.x.xx-kernel)
and commented out every entry in ```./etc/ld.so.preload```

**Comment by sacarde** [comment]
but.. in this situation... can you run:

- lsusb 
- modprobe <somemodule>

without errors?

**Comment by M0Rf30** [comment]
tale a look here https://github.com/M0Rf30/simonpi

**Comment by nachoparker** [comment]
@MoRf30 kernel 4.9! thanks I'll try it for NCP

Is it very different from Raspbian kernels? weird options and stuff?

**Comment by M0Rf30** [comment]
@nachoparker you will find the config files for every kernel.
 scripts are very simple. Fork me and give me suggestions, dmesgs and logs. I will try to update

**Comment by nachoparker** [comment]
my question is: did you base your config or change it fundamentally from the Raspbian kernel config?

I'm trying to save the time to recompile the kernels myself because my hands are pretty full with the rest of [NCP](https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/).

I use it for development, I also came ip with my qemu-system-arm [wrappers for this](https://ownyourbits.com/2017/02/06/raspbian-on-qemu-with-network-access/).

Not really very important, because it's just for developing NCP userland, but for instance, the 4.4 kernel from this repo was missing iptables multiport so fail2ban wasn't working.

**Comment by M0Rf30** [comment]
@nachoparker  config for rpi is similar to this repo config, I've added multiport as you requested and there's no esoteric setting
Same for rpi2 and rpi3.
Let me know if you are in troubles

**Comment by juokelis** [comment]
Try updated kernel. Works with latest stretch image. Although some not nice messages in dmesg, ipv6 not working and similar. Need more tests. Will do that in some time, but you can pick up from here while I'll be away with other project :) https://github.com/juokelis/qemu-rpi-kernel

**Comment by M0Rf30** [comment]
Updated my projects with kernel 4.9.80. Let me know

**Comment by M0Rf30** [comment]
I've updated my projects with your latest patch, I've made an essential modification. You have to use some udev rules in order to properly mount the disk image at boot. See for other details in simonpi code at this commit https://github.com/M0Rf30/simonpi/commit/b691142d380ad377480c7c2722f35675056195ce

**Comment by juokelis** [comment]
Great! Thanks, cound't get rpi3 to work (windows QEMU build is too old), but looks like rpi2 build is working. Will try to get a matching image. Thanks again.

**Comment by M0Rf30** [comment]
Take a look to simonpi docker image:
https://github.com/M0Rf30/simonpi/blob/master/docker/README.md

**Comment by juokelis** [comment]
It would be a bit of overhead to run on Windows Virtualbox, Debian on it with Docker on it and Qemu there :) I'll stick with Qemu on windows for now :) Will manage to get image somehow, from same docker scripts most likely :)

Thanks again!

**Comment by dhruvvyas90** [comment]
Added with the new PR.
