### ISSUE TITLE
linux-arm.patch mismatched with build-kernel-qemu

### ISSUE THREAD

**Issue by dewhisna** [dhruvvyas90/qemu-rpi-kernel#42]
Trying to run `build-kernel-qemu`  to manually build the kernel from the source fails with the following:

```
$ ./build-kernel-qemu 
Cloning into 'linux'...
remote: Counting objects: 5889381, done.
remote: Compressing objects: 100% (40/40), done.
Receiving objects: 100% (5889381/5889381), 1.64 GiB | 4.40 MiB/s, done.
remote: Total 5889381 (delta 19), reused 8 (delta 5), pack-reused 5889336
Resolving deltas: 100% (4901848/4901848), done.
Checking connectivity... done.
Checking out files: 100% (56775/56775), done.
patching file arch/arm/mach-versatile/Kconfig
Hunk #1 FAILED at 4.
Hunk #2 FAILED at 12.
2 out of 2 hunks FAILED -- saving rejects to file arch/arm/mach-versatile/Kconfig.rej
patching file arch/arm/mm/Kconfig
Hunk #1 FAILED at 71.
Hunk #2 FAILED at 89.
Hunk #3 FAILED at 127.
Hunk #5 FAILED at 359.
4 out of 5 hunks FAILED -- saving rejects to file arch/arm/mm/Kconfig.rej
patching file drivers/mmc/host/Kconfig
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- saving rejects to file drivers/mmc/host/Kconfig.rej
```
It appears that the `linux-arm.patch` file is out-of-sync with the `build-kernel-qemu` .  Is there a newer patch file that didn't get committed with the build script?  It would seem that since the script explicitly states which commit to checkout then the patch file it would be using should match the code it's trying to patch.  Or am I missing something?

**Comment by dewhisna** [comment]
Ah, I see what it is.  I had missed the fact that `build-kernel-qemu` by default sets `COMMIT` to an empty string rather than to a commit that this project is compatible with.  I suggest changing:

```
COMMIT=""
```

On line 10 to:

```
COMMIT="rpi-4.4.y"
```

Or perhaps a later branch that's compatible so that your script continues to work out-of-the-box for people who just check it out and try to do a kernel build without editing the script.  `rpi-4.4y` works and the current `rpi-4.9.y` does not.  So it broke somewhere between the two, but I didn't try all of them in between to see where the breakage happened.

Another "fix" would be to have the script require `COMMIT` to be set in the `USE_GIT` case like it does for the non-`USE_GIT` case so that the user knows to set that before trying the build.

I'm leaving this issue open and let you close it when you decide if and how you want to fix the default behavior of your script.

**Comment by dhruvvyas90** [comment]
Hello, I see the behavior. Patch fails with 4.9. Did you find a work around to make it work with kernel 4.9 ? Thanks.

**Comment by dewhisna** [comment]
No, instead of trying to emulate the entire RPi on qemu, I found a much better way.  Use qemu static.  See this wiki on Debian:
https://wiki.debian.org/RaspberryPi/qemu-user-static

Using qemu-static, you can emulate the ARM processor and actually run the vast majority of all native RPi code -- you can even do things like system updates and such to your chroot environment.  But the bigger benefit is that you have the full RAM of your PC to use and not limited to the RAM available on the RPi.

That actually served my needs a whole lot better, as I wasn't wanting to emulate the RPi hardware itself, and so had no need to actually run the RPi Kernel on qemu.  What I really wanted was a native ARM chroot environment to run on my x86 PC to use for compiling code that was too large to compile on the real RPi itself.

The thing I was compiling needed an absolute minimum of 4GB to compile, and so the RPi was running out of resources.  Why not just cross-compile my code with a cross-toolchain, you may wonder?  The reason was that the code I was compiling needed Wine (and in this case an ARM version of Wine) and while Wine will compile for the ARM on the RPi, its build environment isn't setup for doing cross-compiling of Wine, so you can't easily build an ARM Wine running on an x86 PC.

But, using the static-qemu approach at the above link worked marvelously.  I was able to run the RPi apps on my x86 PC as if I was running on the real RPi, only with lots more RAM and was able to successfully compile both Wine and my application in that environment.  And when I was done, all I had to do was flash the image used in the qemu-static process, as described at the link above, to an SDCard and boot my RPi.

Plus, it could be automated on a Jenkins build server easily too, and even allows you to run the test-suite in the ARM environment.

So...  I gave up on these kernel patches.  I don't know what your specific needs are, but if you just want to run ARM apps without emulating the actual RPi hardware, give qemu-static a try...

**Comment by guysoft** [comment]
That is how [CustomPiOS](https://github.com/guysoft/CustomPiOS) works.
See https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/custompios#L22

**Comment by slavkoja** [comment]
E.g. it is not possible to (re)build some packages via qemu-static because some not implemented calls, then it is not full replacement/solution.

**Comment by guysoft** [comment]
Actually packages build great. I mean things like testing in GUI or testing boot sequences.

**Comment by dewhisna** [comment]
Right, there's still a need to do the full RPi emulation and such, and to build a proper kernel.  I wasn't suggesting replacing things entirely with qemu-static.  It's just that for my specific purpose of compiling some ActiveX components for the ARM that needed Wine and that weren't capable of compiling on native RPi hardware due to their intensive Boost template usage that caused it to need 4GB+ of free RAM to compile them, qemu-static worked for my purposes.

Though even that is still a little on the slow side, as it takes about 6-8 times longer to compile while emulating the ARM than it does to compile natively on the PC.  So my long-term solution is to build Wine for ARM with qemu-static (since the Wine build scripts don't easily support cross-compiling toolchains), and then use the cross-toolchain to build the ARM targets for my components on the PC while running native x86 tools.

There will still be a need to do some testing in a proper environment.  So having a RPi kernel built for qemu would be nice.  Though I suppose I can put some real RPi hardware in the loop as a test machine node for our Jenkins build server.

**Comment by guysoft** [comment]
I'm building two raspberrypi real-time kernels,  that takes ~12 hours :-/

**Comment by dhruvvyas90** [comment]
New patch has been added for 4.9.
