### ISSUE TITLE
Unable to access GUI

### ISSUE THREAD

**Issue by sharmaaddy** [dhruvvyas90/qemu-rpi-kernel#44]
Thank you very much for your efforts . I have a small issue while installing the QEMU PI , actually it gets launched be the following command and I get the welcome screen and all :

qemu-system-arm -kernel ~/qemu_vms/qemu-rpi-kernel/kernel-qemu-4.4.21-jessie -cpu arm1176 -m 256 -M versatilepb -serial stdio -append "root=/dev/sda2 rootfstype=ext4 rw" -hda ~/qemu_vms/2017-04-10-raspbian-jessie.img -redir tcp:5022::22 -no-reboot`

but I cannot move the mouse inside
or the arrow buttons doesn't work either.
I highly appreciate your help on this. I am trying to learn ARM processor coding but this is a small bump that I am unable to bypass.

**Comment by guysoft** [comment]
Hey,
So I tested it here and it works ``kernel-qemu-4.4.34-jessie`` and latest stretch:

```
sudo apt-get install qemu git util-linux
git clone https://github.com/guysoft/CustomPiOS.git
wget https://downloads.raspberrypi.org/raspbian/images/raspbian-2017-12-01/2017-11-29-raspbian-stretch.zip
sudo ./CustomPiOS/src/qemu_boot.sh ./2017-11-29-raspbian-stretch.zip
```
![screenshot_20180121_184151](https://user-images.githubusercontent.com/325670/35196456-e9a20254-feda-11e7-9b60-b0fb02ef67e9.png)

**Comment by dhruvvyas90** [comment]
As per previous comment, it should work.
