### ISSUE TITLE
got kernel panic with using "-dtb versatile-pb.dtb"

### ISSUE THREAD

**Issue by EvaChenn** [dhruvvyas90/qemu-rpi-kernel#45]
The reason I use -dtb is that I want to add a self-defined platform device to the device tree.
But I found that I can't make dtb from build-kernel-qemu script (I have already add "make dtb" into build-kernel-qemu).

Also I have tried to use the original linux source code to create versatile-pb.dtb and added to the qemu command with "-dtb versatile-pb.dtb".
But I got "kernel panic... Unable to mount root fs on unknown-block(31,3)" as bellow.
![image](https://user-images.githubusercontent.com/31064582/32777932-17c73e94-c973-11e7-9732-28c0d369c2c6.png)

Does anyone know how to make or use the device tree to this qemu-rpi-kernel?

Thanks for reading this issue.

**Comment by juokelis** [comment]
You need to add CONFIG_PCI_VERSATILE=y before compiling kernel to work with dtb.

**Comment by dhruvvyas90** [comment]
Give it a shot with newer kernel.

**Comment by Jeansen** [comment]
would this also work with versatile express?

**Comment by dhruvvyas90** [comment]
@EvaChenn : Do new comments help you solve your issue ?

**Comment by dhruvvyas90** [comment]
Closed due to inactivity.
