### ISSUE TITLE
Do you plan to release a kernel for the new debian stretch ?

### ISSUE THREAD

**Issue by muawijhe** [dhruvvyas90/qemu-rpi-kernel#48]
I tried to modify the script to accomodate the new kernel, however I didn't find the solution.

Raspbian version I am using:

wget http://director.downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-12-01/2017-11-29-raspbian-stretch-lite.zip

Commit of the raspbian linux kernel (accordingly to a forum post is the one released with the stable raspbian):

raspberrypi-kernel_1.20170811-1

The kernel has been patched accordingly to the previous patch (note the new file is compliant with the specified new kernel). You can download the patch file: [new_kernel_patch.txt](https://github.com/dhruvvyas90/qemu-rpi-kernel/files/1608019/new_kernel_patch.txt)

The kernel is built successfully. 

Using the script in your repo, the image is "formatted" [a few files are modifiled].

When executed, yields to the following command:

qemu-system-arm -kernel qemu-kernel-4.9.41-cpu arm1176 -m 256 -M versatilepb -serial stdio -append "root=/dev/sda2 rootfstype=ext4 rw" -hda formatted_2017-11-29-raspbian-stretch-lite.img

Qemu boots, and 

WARNING: Image format was not specified for 'formatted_2017-11-29-raspbian-stretch-lite.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument
Uncompressing Linux... done, booting the kernel.

Error: unrecognized/unsupported processor variant (0x410fb767).WARNING: Image format was not specified for 'formatted_2017-11-29-raspbian-stretch-lite.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument
Uncompressing Linux... done, booting the kernel.

Error: unrecognized/unsupported processor variant (0x410fb767).

Any ideas?

**Comment by guysoft** [comment]
Raspbian stretch boots fine for me.
You can run this to try:

```
apt-get install qemu git
git clone https://github.com/guysoft/CustomPiOS.git
wget https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-12-01/2017-11-29-raspbian-stretch-lite.zip
sudo ./CustomPiOS/src/qemu_boot.sh ./2017-11-29-raspbian-stretch-lite.zip
```

The qemu_boot.sh script will extract and modify the image inside the zip for you and run it.

**Comment by dhruvvyas90** [comment]
Hi, @muawijhe , I tried to recompile raspberrypi-kernel_1.20170811-1 with given patch. I throws me some errors. I was wondering if you could share your compiled kernel (may be create a PR) if it works with latest raspbian stretch.

**Comment by juokelis** [comment]
Try updated kernel. Works with latest stretch image. Although some not nice messages in dmesg, ipv6 not working and similar. Need more tests. Will do that in some time, but you can pick up from here while I'll be away with other project :) https://github.com/juokelis/qemu-rpi-kernel

**Comment by guysoft** [comment]
@juokelis Does not work for me, on latest raspbian image I ge:
```
/usr/bin/qemu-system-arm -kernel /tmp/kernel-qemu-4.9.59-stretch -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append 'root=/dev/sda2 panic=1 rootfstype=ext4 rw' -hda /tmp/2017-11-29-raspbian-stretch-lite.img -net nic -net user,hostfwd=tcp::8000-:80,hostfwd=tcp::8888-:8888
WARNING: Image format was not specified for '/tmp/2017-11-29-raspbian-stretch-lite.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument
Uncompressing Linux... done, booting the kernel.

Error: unrecognized/unsupported machine ID (r1 = 0x00000183).

Available machine support:

ID (hex)        NAME
ffffffff        Generic DT based system
ffffffff        ARM-Versatile (Device Tree Support)

Please check your kernel config and/or bootloader.
```

**Comment by guysoft** [comment]
@juokelis I wonder - Is there a chance you can build an armv7 kernel?
I am working on Zynthian and there is armv7 stuff there which wont run with this kernel, I get Illegal instruction errors.


Also here is a photo that it works
![screenshot_20180221_000731](https://user-images.githubusercontent.com/325670/36451906-45559b88-169b-11e8-96bd-335bf0d066c1.png)

**Comment by juokelis** [comment]
Check this out - https://github.com/M0Rf30/simonpi - it has working armv71 build for rpi2.

**Comment by guysoft** [comment]
@juokelis That is really cool, but I can't see how to get it to work on a Debian-based distro, since CustomPiOS is mostly Debian.

**Comment by juokelis** [comment]
OK, sorry I'm all into raspbian / osmc :) It's also debian based, shouldn't be too different. Anyway looks like I won't be any help to you :) Good luck.

**Comment by guysoft** [comment]
@juokelis Yes you are, you built a newer kernel, and it would still work on armv6 stuff. 
If you can point me in how to build armv7 then even better :)

**Comment by dhruvvyas90** [comment]
@juokelis: Do you mind creating a PR request to update the new kernel ? I just tested 4.9 kernel from your repo. Seems to be working good.

**Comment by juokelis** [comment]
Sure, check it out. Ping me if done something wrong.

**Comment by dhruvvyas90** [comment]
@juokelis: Thanks, appreciate that. :)
