### ISSUE TITLE
Kernel to run armv7 compiled programs

### ISSUE THREAD

**Issue by guysoft** [dhruvvyas90/qemu-rpi-kernel#50]
Hey,
I have a raspberrypi Image with lots of armv7 programs, but the kernel here is armv6.
Is there a way to run armv7 programs/ build a kernel for armv7?

Thanks,

**Comment by dhruvvyas90** [comment]
In order to run it with armv7 kernel, you should try latest qemu with -M raspi2 option. Hope it helps.

**Comment by guysoft** [comment]
Can you give an example and kernel?
Because a while ago when I did try the raspi2 option it was experimental and only parts of the system worked. I got as far as some of the boot. 
You can see where it failed here:
https://github.com/guysoft/FullPageOS/issues/150#issuecomment-323569988

I also warmly suggest you close the issue after you know its solved, otherwise other people would keep opening it. It gives you also the option to link previous attempts like I did above.
