### ISSUE TITLE
Kernel Panic Unable to mount root fs on unknown-block(31,3)

### ISSUE THREAD

**Issue by 1Sara1** [dhruvvyas90/qemu-rpi-kernel#52]
Using the latest qemu:
qemu-system-arm.exe -kernel C:\Users\a\Downloads\kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -machine versatilepb -cdrom C:\Users\a\Downloads\picore-9.0.3.img

Gives error:
Kernel Panic Unable to mount root fs on unknown-block(31,3)
![qemu-panic-vfs-31-3](https://user-images.githubusercontent.com/38193884/39327086-3720239e-4954-11e8-8218-0940392b9103.JPG)

I have tried different images/kernels with the same result.

**Comment by dhruvvyas90** [comment]
I can't comment on picore.img but if you try it with Raspbian image with modifications (read wiki), you should be able to make it work with latest kernel (4.9.xx).

**Comment by dhruvvyas90** [comment]
Closing the issue due to inactivity.

**Comment by wbochra** [comment]
Hello, I am currentlly having the same problem can you halp me i am trying to emulate a raspberry pi (yocto built image) with qemu and i am having the same error in this post this is the qemu command i am using 
qemu-system-arm -M versatilepb -cpu arm1176 -kernel /home/ubuntu/qemu_vms/qemu-rpi-kernel-master/kernel-qemu-4.4.34-jessie -append "root=/dev/sda2 panic=1 rootfstype=ext3 rw" -hda /home/ubuntu/build/tmp/deploy/images/raspberrypi/core-image-minimal-raspberrypi-20210320134208.rootfs.ext3 -m 256 -no-reboot -net nic -net user,hostfwd=tcp::5022-:22
