### ISSUE TITLE
Enable VirtFS By Default

### ISSUE THREAD

**Issue by CuriousTommy** [dhruvvyas90/qemu-rpi-kernel#53]
VirtFS is a feature QEMU provides to allows the host to share a folder with the guest. However, the driver is not compiled on the prebuilt kernal by default. Since these kernals are meant to be used with qemu, I was wondering if you would be willing to add to the following config options to the `.config` part of script:

```
CONFIG_NET_9P=y
CONFIG_NET_9P_VIRTIO=y
CONFIG_9P_FS=y
CONFIG_9P_FS_POSIX_ACL=y
CONFIG_PCI=y
CONFIG_VIRTIO_PCI=y
```
[*taken from qemu wiki](https://wiki.qemu.org/Documentation/9psetup)

I can even do a pull request if you like.

**Comment by dhruvvyas90** [comment]
@CuriousTommy : If you have compiled kernels ready with this configs, feel free to send a PR.

**Comment by CuriousTommy** [comment]
@dhruvvyas90 Just to be clear, do you want me to also include the prebuild kernel in the PR? If so, do you want me to replace the most recent one (`4.9.59`)?

**Comment by dhruvvyas90** [comment]
@CuriousTommy: Yes, prebuilt version of the kernel would be great. Adding a new kernel "with_VirtFS" suffix in name should do. Thanks a lot.
