### ISSUE TITLE
QEMU CIFS

### ISSUE THREAD

**Issue by gump74** [dhruvvyas90/qemu-rpi-kernel#54]
Greetings,
I would like to start by thanking you for your efforts. I was able to get my rpi img to work however, I was not able to get cifs to work due to the fact that it was not compiled into the kernel. I tried to manually add the CIFS to the kernel with the ncurses menu. In the ncurses menu I did load the config file. I don't know if that was right. After the ncurses menu I am prompted with hundreds of questions. The resulting kernel does not work. I think the reason that it does not work is the fact that I have no idea what I am doing. Would you be able to write an instruction sheet on how to do this properly? Would it be possible to include CIFS in future? Also one small note, the build script was not working so I commented out the exit above the make section. I'm not sure if I was doing it correctly.

**Comment by gump74** [comment]
I had replied to the e-mail, ... you're not supposed to do that! CIFS lets you mount the smb shares, in my case it is my server. I have never successfully compiled a kernel before, actually before the other day I have never compiled a kernel before. I suppose it would help if I had even a vague understanding of what needed to be done.

**Comment by gump74** [comment]
You mentioned you were trying to get virtfs compiled, did you get that to work? Maybe I could figure out how to add cifs by following what you did.

**Comment by CuriousTommy** [comment]
> You mentioned you were trying to get virtfs compiled, did you get that to work?

I was able to produce a working kernel. I am able to create and modify files between guest and host. I just need to add the new kernel to my fork and submit a pull request.

> Maybe I could figure out how to add cifs by following what you did.

Just so I understand, what exactly do you mean by "The resulting kernel does not work"? Were you able to compile the kernel?

If you are wondering how I built the kernel, I followed the Kernel Building guide on [raspberrypi.org](https://www.raspberrypi.org/documentation/linux/kernel/building.md) first, then I tried to use the script (FYI: follow the instructions for `Cross-compiling`).

**Comment by gump74** [comment]
It did compile a kernel but qemu failed to load the img with the kernel that I compiled. It did load the OS when I used the kernel from this repo. I will try to run through that article and see if I can make a working kernel.

**Comment by gump74** [comment]
That article does not address the primary problem that I seem to be facing. When the compile starts it asks if I should repatch, if I say no then it does not do anything. If I say yes to those questions then it goes into an ncurses menu. That menu can do a load, loading the config file. After that I am prompted by several hundred questions. Should I just choose the default? what should I be doing at that point?

**Comment by dhruvvyas90** [comment]
Closed due to inactivity.
