### ISSUE TITLE
Latest Raspbian version uses kernel 4.14

### ISSUE THREAD

**Issue by me21** [dhruvvyas90/qemu-rpi-kernel#55]
Can you please prepare the kernel for the latest Raspbian image?

**Comment by nicolai86** [comment]
Is there any documentation on how to build/ patch a kernel? Looks like the author is busy and it might be an opportunity to help.

**Comment by Richardgriff** [comment]
Hi Have you manged to get the 4.14 to work

**Comment by dhruvvyas90** [comment]
@nicolai86: Feel free to create a PR, if you've a working 4.14 kernel ready. If not, I will give a shot this weekend. Thanks.

**Comment by jlaine** [comment]
I was able to boot the latest Raspbian images using #60

**Comment by dhruvvyas90** [comment]
@jlaine: Merged your PR. Appreciate your help.

**Comment by jlaine** [comment]
Cool! Going forward it might be worth clarifying which files apply to which kernel.
