### ISSUE TITLE
Enable v9fs (p9) for sharing files between host and guest.

### ISSUE THREAD

**Issue by Jeansen** [dhruvvyas90/qemu-rpi-kernel#57]
I followed https://wiki.qemu.org/Documentation/9psetup to share files between a host and qemu running the remulated raspian. Unfortunately the 9p file system is unknown and there are no modules available at all for this kernel.

It would be great, if this feature were compiled into the kernel. Though I am a bit puzzled, because in the build script I see, that is is actually enabled.

Either way, please compile the kernel with this feather or enlighten me on how to get it up and running correctly :)

Keep up the good work!

**Comment by CuriousTommy** [comment]
> It would be great, if this feature were compiled into the kernel. Though I am a bit puzzled, because in the build script I see, that is is actually enabled.

Yeah, I was the one who submitted a pull request to enable this feature. [I even added a premade kernal also](https://github.com/dhruvvyas90/qemu-rpi-kernel/blob/master/kernel-qemu-4.9.59-stretch_with_VirtFS)

**Comment by Jeansen** [comment]
Oh, I see. I totally overlooked that one .... Thank you! :)

**Comment by Jeansen** [comment]
@CuriousTommy Anyway, could you tell how you build it?

**Comment by CuriousTommy** [comment]
I followed the [kernel building guide (Cross-compiling) on raspberrypi.org](https://www.raspberrypi.org/documentation/linux/kernel/building.md) to understand how to compile the raspberry pi kernel.

Then I tried to build the kernel using the build script. Make sure you comment out the [exit](https://github.com/dhruvvyas90/qemu-rpi-kernel/blob/master/tools/build-kernel-qemu#L45), or the script will quit before it compiles.

**Comment by Jeansen** [comment]
@CuriousTommy Thank you for the hints. I'll try that :smiley:
