### ISSUE TITLE
Updating the jessie image with Linux in VirtualBox

### ISSUE THREAD

**Issue by DFKSingleton** [dhruvvyas90/qemu-rpi-kernel#58]
I had downloaded the jessie image on my windows system. I then wanted wanted to follow the instructions supplied to update the jessie image in my Linux system installed in VirtualBox on my Windows machine. I used the "shared directory" feature of VirtualBox to try to mount the image. This failed repeatedly. The solution was to copy the image-file from the shared directory to a directory within the Linux machine. I could then mount the image without any problem.

I hope this helps someone else

David Singleton

**Comment by dhruvvyas90** [comment]
@DFKSingleton: If you can create a wiki note on the same topic, that'd be great.
