### ISSUE TITLE
Is there a Kernel for Raspian Jessie and Jessie-Lite v4.9.35-v7 (raspbian-2017-07-05)

### ISSUE THREAD

**Issue by simspace-dr** [dhruvvyas90/qemu-rpi-kernel#59]
I have 14 RasPis running Raspbian-2017-07-05 (Jessie-Lite v4.9.35-v7).

I'm new to QEMU and would like to setup an emulator on my Linux laptop for building an testing apps for Jessie and Jessie-Lite v4.9.35-v7 (raspbian-2017-07-05)? 

Is that kernel available anywhere for QEMU?

Thanks,
Chris

**Comment by elliotmoule** [comment]
I'm in a situation as @simspace-dr, though using Raspbian Stretch ARM32v7, and wondering if anyone can point me in the direction of a way to run that in the QEMU emulator? :) 

Regards,

Elliot.

**Comment by vfdev-5** [comment]
Maybe [this](https://github.com/vfdev-5/qemu-rpi2-vexpress) can help :)

**Comment by dhruvvyas90** [comment]
@simspace-dr : I'm not sure if Jessie-Lite kernels are different than Jessie but you can check out 4.9.35 kernel on the repo to see compatibility. Thanks.
