### ISSUE TITLE
minor update to README requested

### ISSUE THREAD

**Issue by ebo** [dhruvvyas90/qemu-rpi-kernel#66]
In the README below at the end you mention: "Go through wiki page for step by step guide..."  Can you provide a link to the wiki page?  I am not sure where it is as I ahve just found qemu-rpi-kernel.  Thanks!

**Comment by dhruvvyas90** [comment]
@ebo : Added link.

**Comment by ebo** [comment]
Thanks ;-)  I will probably have a dozen or more questions over the next week  8-/
