### ISSUE TITLE
drive with bus=0, unit=0 (index=0) exists (Double Quotes vs Single Quotes)

### ISSUE THREAD

**Issue by dbelliss** [dhruvvyas90/qemu-rpi-kernel#71]
I was trying to follow this guide to run rasbian on QEMU on windows 10x64, and I created a start.bat to run in command prompt with a command based on the contents of the README.

The line 
`-append 'root=/dev/sda2 panic=1' \`

Was causing this error:
`qemu-system-arm: -append 'root=/dev/sda2: drive with bus=0, unit=0 (index=0) exists\`

I was able to fix this by replacing the single quotes with double quotes. Not sure if this is platform specific to windows or not though.

**Comment by dhruvvyas90** [comment]
@dbelliss : Could be platform specific.
