### ISSUE TITLE
Error creating machine in libvirt

### ISSUE THREAD

**Issue by mbprado** [dhruvvyas90/qemu-rpi-kernel#72]
running directly from qemu, it runs ok. however, it is impossible to make it run with libvirt. 

virt-install   --name pi   --arch armv7l   --machine versatilepb   --cpu arm1176   --vcpus 1   --memory 256   --import   --disk 2018-11-13-raspbian-stretch-full.img,format=raw,bus=virtio  --network user,model=virtio  --video vga --graphics spice --rng device=/dev/urandom,model=virtio --boot 'dtb=qemu-rpi-kernel/versatile-pb.dtb,kernel=qemu-rpi-kernel/kernel-qemu-4.14.79-stretch,kernel_args=root=/dev/vda2 panic=1' --events on_reboot=destroy

Starting install...
ERROR    XML error: No PCI buses available
Domain installation does not appear to have been successful.

**Comment by elpeter25** [comment]
Same error here.
Did anyone manage to create a VM?

**Comment by muelli** [comment]
I am running Ubuntu 18.04 and have the same problem.
