### ISSUE TITLE
More CPUs and RAM

### ISSUE THREAD

**Issue by nemiah** [dhruvvyas90/qemu-rpi-kernel#73]
Hello,
thank you for this project, everything works.

Is it possible to add more RAM and more CPUs to the virtual machine?

I tried starting qemu-system-arm with -m 1G and -smp 4 but it tells me that
versatilepb: memory size must not exceed 256MB
and
invalid SMP CPUs 4. The max CPUs supported by machine 'versatilepb' is 1

Best wishes
Nena

**Comment by dhruvvyas90** [comment]
Qemu now supports out of the box raspi2 machine emulation that should have multiple CPU options with increased memory. Check it out.

**Comment by nemiah** [comment]
Thank you for this information, I'll take a look!
