### ISSUE TITLE
Bad register offset

### ISSUE THREAD

**Issue by Bahir** [dhruvvyas90/qemu-rpi-kernel#75]
That's what I receive when running

bash-5.0$ sh -x run.sh
qemu-system-arm -M versatilepb -cpu arm1176 -m 256 -drive file=./2018-11-13-raspbian-stretch-lite.img,index=0,media=disk,format=raw -net nic -net user,hostfwd=tcp::5022-:22 -dtb ./versatile-pb.dtb -kernel ./kernel-qemu-4.14.79-stretch -append 'root=/dev/sda2 panic=1' -no-reboot

vpb_sic_write: Bad register offset 0x2c

**Comment by chpatton013** [comment]
I fixed this by adding `-serial stdio` to my command.

**Comment by dhruvvyas90** [comment]
@Bahir : Does the latest comment solve your problem ?

**Comment by radeksimko** [comment]
I'm getting the same error, running the following:

```
qemu-system-arm \
	-append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" \
	-boot c \
	-cpu arm1176 \
	-drive "file=2019-04-08-raspbian-stretch-lite.img,if=scsi,cache=none,discard=ignore,format=raw" \
	-kernel ./kernel-qemu-stretch \
	-dtb ./versatile-pb.dtb \
	-m 256M \
	-machine type=versatilepb,accel=tcg \
	-name packer-qemu \
	-no-reboot \
	-vnc 127.0.0.1:4 \
	-nic user,id=user.0,hostfwd=tcp::5555-:22
```

Adding `-serial stdio` doesn't make the error go away for me, it just append more output after this error (as expected by the nature of the flag?).

**Comment by iluxave** [comment]
I see same error with and without -serial stdio flag on Qemu 4.0.0 and Qemu 2.12.1

**Comment by minusplusminus** [comment]
to block any `ctrl+c` action and opening the window,` -display none -serial mon:stdio` worked best for me

**Comment by victoryang00** [comment]
for my case, I did it with:
```bash
qemu-system-aarch64 -M versatilepb \
                    -cpu arm1176 -hda 2019-09-26-raspbian-buster-full.img \
                    -net nic -net user,hostfwd=tcp::5022-:22 \ 
                    -dtb qemu-rpi-kernel/versatile-pb.dtb \
                    -kernel qemu-rpi-kernel/kernel-qemu-4.19.50-buster \
                    -m 256 -append "root=/dev/sda2" \
                    -no-reboot -serial stdio
```

**Comment by scottfurry** [comment]
Getting this error as well. Using `-serial stdio` does not appear to affect situation.
Found source code reference to [versatilepb.c](https://github.com/qemu/qemu/blob/f884294bd76eb89127d311627d8de1b70ec9ba54/hw/arm/versatilepb.c#L116) showing value `0x2c` not listed in switch statement. My guess is change in function signature or mis-ordering of arguments but I could be wrong.

**Comment by Jukoo** [comment]
> I fixed this by adding `-serial stdio` to my command.



> for my case, I did it with:
> 
> ```shell
> qemu-system-aarch64 -M versatilepb \
>                     -cpu arm1176 -hda 2019-09-26-raspbian-buster-full.img \
>                     -net nic -net user,hostfwd=tcp::5022-:22 \ 
>                     -dtb qemu-rpi-kernel/versatile-pb.dtb \
>                     -kernel qemu-rpi-kernel/kernel-qemu-4.19.50-buster \
>                     -m 256 -append "root=/dev/sda2" \
>                     -no-reboot -serial stdio
> ```

I approved ...  💯
