### ISSUE TITLE
Kernel x Jessie

### ISSUE THREAD

**Issue by mariohmol** [dhruvvyas90/qemu-rpi-kernel#8]
I'm trying to boot jessie version , tested with your 2 versions of kernel and from others repo as well, always get the error:

* Kernel panic - not syncing : Attempted to kill init

Tested using image 2016-02-09-raspbian-jessie.img and this cmd : 

* qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -hda 2016-02-09-raspbian-jessie.img

I'm using newest OSX and when i double click the img, it mounts but i can see the file as you point here:

* https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.1.x-kernel

I think that the first thing would point what version of jessie it worked for you, so i can test using this same version, and if is possible doc in readme/wiki =) 

Thanks!

**Comment by mariohmol** [comment]
I could make work using old versions (kernel and raspbien) 

* qemu-system-arm -kernel kernel-qemu-3.10.25-wheezy -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" -hda 2012-12-16-wheezy-raspbian.img

**Comment by dhruvvyas90** [comment]
I've tested jessie kernels on repo with 2015-11-21 and 2015-09-25 jessie images. I do not have the latest image. Let me download and test. I will let you know.

**Comment by mariohmol** [comment]
Wheezy version works. but when i use startx (using root or pi) , it shows me the view but mouse/keyboard not works..

**Comment by mariohmol** [comment]
mouse worked after doing the steps described here: 

* https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki

I thought that this were just for jessie version

**Comment by mariohmol** [comment]
The steps that i did are here: 

* https://github.com/mariohmol/raspberrypi-selfie

**Comment by dhruvvyas90** [comment]
Did you make necessary changes in .img file like it specifies in wiki before trying to emulate with the kernel on the repo ?

**Comment by mariohmol** [comment]
Sorry, my mistake, there is:

* https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.1.x-kernel

I'm using OSx and i could not reproduce this steps. See that i did:

i can read boot partition in image file:

````
hdiutil  attach 2016-02-09-raspbian-jessie.img 
/dev/disk2          	FDisk_partition_scheme         	
/dev/disk2s1        	Windows_FAT_32                 	/Volumes/boot
/dev/disk2s2        Linux  
`````

I can unmount boot disk:

````
hdiutil unmount /dev/disk2s1
"/dev/disk2s1" unmounted successfully.
````


If i try to mount linux , it gives me error:

````
mount /dev/disk2s2
hdiutil: mount failed - sistemas de arquivos não montáveis
````

But if i mount boot, it works:

````
mount /dev/disk2s1
/dev/disk2s1        Windows_FAT_32                 /Volumes/boot
````


Here is the description of the partitions:

````

hdiutil pmap 2016-02-09-raspbian-jessie.img 

MEDIA: ""; Size 4 GB (8060928 x 512); Max Transfer Blocks 2048

SCHEME: 1 MBR, "PC Partition Scheme" [8]

SECTION: 1 Type:'MAP'; Size 4 GB; Offset: 0 - 8060928, (8060928 x 512); Overhead 1

ID Type                 Offset       Size         Name                      (3)

-- -------------------- ------------ ------------ -------------------- --------

 0 MBR                             0            1                     

   Free                            1         8191

 1 Windows_FAT_32               8192       122880                     

 2 Linux                      131072      7929856    

````



Is possible to attach ussing sectors (offset):



https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/hdiutil.1.html


````
-section subspec
Attach a subsection of a disk image.  subspec is any of <offset>, <first-last>, or <start,count> in 0-based sectors.  Ranges are inclusive.
````

Then tryied to attached with section

````
hdiutil  attach 2016-02-09-raspbian-jessie.img -section 131072,7929856
hdiutil: attach failed - Recurso temporariamente indisponível

or

hdiutil  attach 2016-02-09-raspbian-jessie.img -section 131072
````



If attached without section, it works


````
hdiutil  attach 2016-02-09-raspbian-jessie.img
/dev/disk2          	FDisk_partition_scheme         	
/dev/disk2s1        	Windows_FAT_32                 	/Volumes/boot
/dev/disk2s2        Linux  
````


really lost here!

**Comment by mariohmol** [comment]
Using diskutil i have same issue. Found that the Problem about ext4.

Could not install this:
https://sourceforge.net/p/fuse-ext2/discussion/787602/thread/754d1615/

All opensource are readonly.
https://github.com/gerard/ext4fuse

Going to make a vmbox with ubuntu, to get this image and make the changes.

**Comment by mariohmol** [comment]
Closing for now, after that if i have problems we can continue. Thanks!

**Comment by dhruvvyas90** [comment]
@mariohmol: As of now, I don't know any **free** utility that could be used to read and write an ext4 on Mac OS X, but you can do it in virtual box or something running linux. There are few paid options like paragon and others, but I haven't tested if they could be used to mount an ext4 to modify the data as mentioned in wiki. If you come up with a better solution to tackle this issue, do let us know.
