### ISSUE TITLE
Are there any methods to use larger memory?

### ISSUE THREAD

**Issue by AlucardNosferatu** [dhruvvyas90/qemu-rpi-kernel#82]
-M versatilepb restrict the memory configuration to be no more than 256MB, are there any ways to use a larger memory? my virtual system runs sluggishly...

**Comment by dhruvvyas90** [comment]
@AlucardNosferatu : Currently, no. Since it is a limitation of versatilepb. Afaik, Qemu was on route to have native rpi2 support. Feel free to check it out. In that case, you don't need modified kernel.

**Comment by AlucardNosferatu** [comment]
Ok, I will check it, Thank you very much!
