### ISSUE TITLE
wiki: error about disk image format

### ISSUE THREAD

**Issue by stephen144** [dhruvvyas90/qemu-rpi-kernel#9]
Regarding the wiki, I encountered this error when specifying the image with:

`-hda posbox.img`

> WARNING: Image format was not specified for 'posbox.img' and probing guessed raw. Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted. Specify the 'raw' format explicitly to remove the restrictions.

I had to use this instead as per the qemu [manual](http://qemu.weilnetz.de/qemu-doc.html#sec_005finvocation):

`-drive file=posbox.img,index=0,media=disk,format=raw`

**Comment by dhruvvyas90** [comment]
As far as I know, it is just a warning, and hence it's safe to use it with `-hda` argument. But yes, you're right, it would be wise to use `-drive` just to be on safe side. Feel free to change wiki, after successful testing.

**Comment by dhruvvyas90** [comment]
@stephen144:  Closing this issue since it is just a warning and emulation works fine with `-hda` argument. Although, this warning can be avoided by using `-drive` option.
