### ISSUE TITLE
aarch64/arm64 kernel

### ISSUE THREAD

**Issue by guysoft** [dhruvvyas90/qemu-rpi-kernel#99]
Hey, I have a 64bit image based on: https://wiki.ubuntu.com/ARM/RaspberryPi

**Comment by xieydd** [comment]
Can you provide aarch64/arm64 kernel @guysoft

**Comment by guysoft** [comment]
@xieydd Raspbian ships with a aarch64 bit kernel:
https://www.raspberrypi.org/forums/viewtopic.php?t=250730

I am not sure how to go about building one, because that would require a 64bit toolchain and I am not sure how to set that up. I have a vague idea but I would need help from someone already building it. And I don't know how to build this repo.

**Comment by dhruvvyas90** [comment]
I believe that one should be able to use Qemu's aarch64 (qemu-system-aarch64) emulation to emulate 64 bit Raspberry pi with raspi2 machine option with shipped kernel and image without modification. I haven't tried it, though.

**Comment by guysoft** [comment]
@dhruvvyas90 
Hey, did some testing, its unable to do networking or keyboard taps, full information in this comment: https://github.com/dhruvvyas90/qemu-rpi-kernel/issues/100#issuecomment-609785010

**Comment by dhruvvyas90** [comment]
@guysoft : Please check additional instructions on how to use native qemu machine raspi2/raspi3 under native-emulation folder. You would need Qemu 5.1 + in order to use keyboard afaik.
